version: '3.8'

services:
  messenger_mongodb:
    container_name: messenger_mongodb
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    volumes:
      - /var/lib/messenger_mongodb/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${mongodb_username}
      MONGO_INITDB_ROOT_PASSWORD: ${mongodb_password}

  messenger_elastic:
    container_name: messenger_elastic
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /var/lib/messenger_elastic/data
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      xpack.security.transport.ssl.enabled: false
      xpack.security.enabled: false

networks:
  default:
    driver: bridge