spring:
  elasticsearch:
    username: ${elasticsearch_username}
    password: ${elasticsearch_password}
  data:
    mongodb:
      host: ${mongodb_host}
      username: ${mongodb_username}
      password: ${mongodb_password}
      database: messenger

app:
  auth:
    tokenSecret: ${security_secret}
    tokenExpirationMSec: 86400000 # 24 hours
    tokenPrefix: "Bearer "
    headerString: "Authorization"
    cors:
      allowedOrigins: http://localhost:8080, http://localhost:3000
  database:
    elasticHost: ${elasticsearch_host}
