server:
  port: 80

spring:
  elasticsearch:
    username: ${elasticsearch_username}
    password: ${elasticsearch_password}

app:
  auth:
    tokenSecret: ${security_secret}
    tokenExpirationMSec: 86400000
    tokenPrefix: "Bearer "
    headerString: "Authorization"
    cors:
      allowedOrigins: http://130.61.181.245:80
  database:
    elasticHost: ${elasticsearch_host}
