app:
  auth:
    tokenSecret: ${security_secret}
    tokenExpirationMSec: 86400000
    tokenPrefix: "Bearer "
    headerString: "Authorization"
    cors:
      allowedOrigins: http://localhost:8080, http://localhost:3000

spring:
  elasticsearch:
    username: ${elasticsearch_username}
    password: ${elasticsearch_password}
